version: "3.8"
services:
  postgres:
    image: postgres:13.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=trello
      - POSTGRES_DB=trello
    volumes:
      - ./data:/var/lib/postgresql/data
